apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: helm-app
  namespace: openshift-gitops
spec:
  destination:
    namespace: chartdemo
    server: https://kubernetes.default.svc
  project: default
  source:
    path: helm/helmfile/demo
    repoURL: https://github.com/christianh814/gitops-examples
    targetRevision: main
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
