apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: bookinfo-bootstrap
  namespace: openshift-gitops
spec:
  destination:
    server: https://kubernetes.default.svc
    namespace: bookinfo-base
  project: default
  source:
    path: bookinfo/instance/overlays
    repoURL: https://github.com/dasong666/my-demo-apps.git
    targetRevision: HEAD
  syncPolicy:
    automated: {}
