apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: service-mesh-test
  namespace: openshift-gitops
spec:
  destination:
    server: https://kubernetes.default.svc
    namespace: istio-system-test
  project: default
  source:
    path: servicemesh/instance/overlays/test
    repoURL: https://github.com/dasong666/cluster-gitops-fork1-repo.git
    targetRevision: HEAD
  syncPolicy:
    automated: {}
